--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Dvaelin121/KeepInventory
build-by-default: true
branches:
- main
projects:
  KeepInventory:
    path: ""
    Icon: "icon.png"
    lint:
      phpstan: false
...
